spring.application.name=student-management-backend
server.port=7088
spring.datasource.url=jdbc:mysql://localhost:3306/db2
spring.datasource.username=root
spring.datasource.password=MoniDB@05
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
